// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbmaKFRRdIukQt-m-1jeqUyLW1SqD4PY',
    appId: '1:944188011459:web:25df4310f5fdca863d8376',
    messagingSenderId: '944188011459',
    projectId: 'cuposuao',
    authDomain: 'cuposuao.firebaseapp.com',
    storageBucket: 'cuposuao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnKVvqPd2VHsMqAPF-aKe_3HmyvIGgjR8',
    appId: '1:944188011459:android:bf8a718f1c1669dd3d8376',
    messagingSenderId: '944188011459',
    projectId: 'cuposuao',
    storageBucket: 'cuposuao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAc_ak7CgvP8gaNp_d_6jq2IcJ9wz4xl8',
    appId: '1:944188011459:ios:677d98bd6a9e92e23d8376',
    messagingSenderId: '944188011459',
    projectId: 'cuposuao',
    storageBucket: 'cuposuao.firebasestorage.app',
    iosBundleId: 'com.example.flutterCuposuao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAc_ak7CgvP8gaNp_d_6jq2IcJ9wz4xl8',
    appId: '1:944188011459:ios:677d98bd6a9e92e23d8376',
    messagingSenderId: '944188011459',
    projectId: 'cuposuao',
    storageBucket: 'cuposuao.firebasestorage.app',
    iosBundleId: 'com.example.flutterCuposuao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgbmaKFRRdIukQt-m-1jeqUyLW1SqD4PY',
    appId: '1:944188011459:web:98cd78fca0de3a143d8376',
    messagingSenderId: '944188011459',
    projectId: 'cuposuao',
    authDomain: 'cuposuao.firebaseapp.com',
    storageBucket: 'cuposuao.firebasestorage.app',
  );

}